Removed jquery-ui from script registration as WP natively includes this library
ArloSoftware/arlowp-plugin pull request #456
Opened 2021-03-12 00:56 UTC by GEOFAIRY

Work item 54673 for details

2021-03-12 01:00 UTC, ry167 requested changes

2021-03-12 01:00 UTC, ry167 commented on admin/class-arlo-for-wordpress-admin.php
> -			wp_enqueue_script( $this->plugin_slug . '-admin-script', plugins_url( 'assets/js/admin.js?20170424', __FILE__ ), array( 'jquery' ), VersionHandler::VERSION, true );
There should be a dependency code we can include in the third parameter to tell WP we need jQuery UI

2021-03-15 02:48 UTC, ry167 requested changes

2021-03-15 02:48 UTC, ry167 commented on admin/class-arlo-for-wordpress-admin.php
> +			wp_enqueue_script( $this->plugin_slug . '-plugin-script-cookie', plugins_url( '../public/assets/js/libs/js.cookie.js', __FILE__ ), array( 'jquery', 'jquery-ui-core' ), VersionHandler::VERSION );
I don't think this will need it?

2021-03-15 02:48 UTC, ry167 commented on admin/class-arlo-for-wordpress-admin.php
> +			wp_enqueue_script( $this->plugin_slug . '-arlo-for-wordpress-script', plugins_url( 'assets/js/arlo_for_wordpress.js?20170424', __FILE__ ), array( 'jquery', 'jquery-ui-core' ), VersionHandler::VERS
does this have a dependency on the cookie script? May as well add it while we are tidying this up.

2021-03-15 02:48 UTC, ry167 commented on admin/class-arlo-for-wordpress-admin.php
> +			wp_enqueue_script( $this->plugin_slug . '-fancybox', 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.js', array('jquery', 'jquery-ui-core'), '3.3.7', true );
This doesn't depend on jquery UI https://fancyapps.com/fancybox/3/docs/

2021-03-15 04:42 UTC, mcdong429 commented on admin/class-arlo-for-wordpress-admin.php
> -			wp_enqueue_script( $this->plugin_slug . '-jquery-ui', plugins_url( 'assets/js/lib/jquery-ui.min.js', __FILE__ ), array( 'jquery' ), VersionHandler::VERSION, true );
Can you also remove the jquery-ui.min.js and jquery-ui.min.css files if they are no longer needed? 

As well as the reference to jquery-ui.min.css at [#L176](https://github.com/ArloSoftware/arlowp-plugin/blob/bbb3ded7ec43e5d2749f33a8c6a54040128f13ba/admin/class-arlo-for-wordpress-admin.php#L176)

2021-03-16 04:25 UTC, mcdong429 reviewed
Looks ok to me.

2021-03-16 04:27 UTC, mcdong429 approved these changes

2021-03-16 05:20 UTC, merged